# Generated by Django 2.1.4 on 2019-01-22 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=500)),
                ('middle_name', models.CharField(blank=True, default='', max_length=500)),
                ('last_name', models.CharField(blank=True, default='', max_length=500)),
                ('date_of_birth', models.DateField(null=True)),
                ('email_id', models.EmailField(blank=True, default='', max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('current_address_1', models.CharField(max_length=600)),
                ('current_address_2', models.CharField(blank=True, default='', max_length=600)),
                ('current_city', models.CharField(max_length=600)),
                ('permanent_address_1', models.CharField(max_length=600)),
                ('permanent_address_2', models.CharField(blank=True, default='', max_length=600)),
                ('permanent_city', models.CharField(max_length=600)),
                ('occupation', models.CharField(choices=[('SR', 'Working'), ('ST', 'Studying')], default='ST', max_length=2)),
                ('company_name', models.CharField(blank=True, default='', max_length=600)),
                ('company_contact_person', models.CharField(blank=True, default='', max_length=600)),
                ('company_contact_number', models.CharField(blank=True, default='', max_length=30)),
                ('company_address_1', models.CharField(blank=True, default='', max_length=600)),
                ('company_address_2', models.CharField(blank=True, default='', max_length=600)),
                ('company_city', models.CharField(blank=True, default='', max_length=600)),
                ('guest_photo', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guesthouse',
            fields=[
                ('gh_id', models.AutoField(primary_key=True, serialize=False)),
                ('html_meta_title', models.CharField(max_length=256, unique=True)),
                ('html_meta_name', models.CharField(blank=True, default='', max_length=256)),
                ('seo_keywords', models.CharField(blank=True, default='', max_length=256)),
                ('gh_name', models.CharField(max_length=100)),
                ('tag_line', models.CharField(blank=True, default='', max_length=50)),
                ('show_copyright', models.BooleanField(default=False)),
                ('copyright_year', models.CharField(blank=True, default='', max_length=4)),
                ('gh_address1', models.CharField(blank=True, default='', max_length=1000)),
                ('gh_address2', models.CharField(blank=True, default='', max_length=1000)),
                ('gh_city', models.CharField(blank=True, default='', max_length=256)),
                ('gh_state', models.CharField(blank=True, default='', max_length=256)),
                ('gh_zip', models.CharField(blank=True, default='', max_length=256)),
                ('gh_country', models.CharField(blank=True, default='', max_length=256)),
                ('phone_support_available', models.BooleanField(default=False)),
                ('support_phonenumber', models.CharField(blank=True, default='', max_length=50)),
                ('phone_support_start_time', models.TimeField(blank=True, null=True)),
                ('phone_support_end_time', models.TimeField(blank=True, null=True)),
                ('phone_support_days', models.CharField(blank=True, default='', max_length=50)),
                ('show_promotion_section', models.BooleanField(default=False)),
                ('number_of_promotion_slides', models.IntegerField(blank=True, null=True)),
                ('show_featured_section', models.BooleanField(default=False)),
                ('featured_header', models.CharField(blank=True, default='', max_length=50)),
                ('number_of_featured_slides', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pin_city_state_country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taluk', models.CharField(max_length=500, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guesthouse.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guesthouse.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Pin_code',
            fields=[
                ('pin_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('state_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guesthouse.Country')),
            ],
        ),
        migrations.AddField(
            model_name='pin_city_state_country',
            name='pin_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guesthouse.Pin_code'),
        ),
        migrations.AddField(
            model_name='pin_city_state_country',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guesthouse.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guesthouse.State'),
        ),
        migrations.AddField(
            model_name='booking',
            name='company_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_addr_country', to='guesthouse.Country'),
        ),
        migrations.AddField(
            model_name='booking',
            name='company_pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_addr_pin_code', to='guesthouse.Pin_code'),
        ),
        migrations.AddField(
            model_name='booking',
            name='company_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_addr_state', to='guesthouse.State'),
        ),
        migrations.AddField(
            model_name='booking',
            name='current_country',
            field=models.ForeignKey(default='IND', on_delete=django.db.models.deletion.PROTECT, related_name='current_addr_country', to='guesthouse.Country'),
        ),
        migrations.AddField(
            model_name='booking',
            name='current_pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_addr_pin_code', to='guesthouse.Pin_code'),
        ),
        migrations.AddField(
            model_name='booking',
            name='current_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_addr_state', to='guesthouse.State'),
        ),
        migrations.AddField(
            model_name='booking',
            name='gh_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guesthouse.Guesthouse'),
        ),
        migrations.AddField(
            model_name='booking',
            name='permanent_country',
            field=models.ForeignKey(default='IND', on_delete=django.db.models.deletion.PROTECT, related_name='permanent_addr_country', to='guesthouse.Country'),
        ),
        migrations.AddField(
            model_name='booking',
            name='permanent_pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permanent_pin_code', to='guesthouse.Pin_code'),
        ),
        migrations.AddField(
            model_name='booking',
            name='permanent_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permanent_addr_state', to='guesthouse.State'),
        ),
        migrations.AlterUniqueTogether(
            name='pin_city_state_country',
            unique_together={('pin_code', 'city', 'taluk', 'state', 'country')},
        ),
    ]
