# Generated by Django 2.1.4 on 2019-01-22 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=500)),
                ('middle_name', models.CharField(blank=True, default='', max_length=500)),
                ('last_name', models.CharField(blank=True, default='', max_length=500)),
                ('date_of_birth', models.DateField(null=True)),
                ('email_id', models.EmailField(blank=True, default='', max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('current_address_1', models.CharField(max_length=600)),
                ('current_address_2', models.CharField(blank=True, default='', max_length=600)),
                ('current_city', models.CharField(max_length=600)),
                ('permanent_address_1', models.CharField(max_length=600)),
                ('permanent_address_2', models.CharField(blank=True, default='', max_length=600)),
                ('permanent_city', models.CharField(max_length=600)),
                ('occupation', models.CharField(choices=[('SR', 'Working'), ('ST', 'Studying')], default='ST', max_length=2)),
                ('company_name', models.CharField(blank=True, default='', max_length=600)),
                ('company_contact_person', models.CharField(blank=True, default='', max_length=600)),
                ('company_contact_number', models.CharField(blank=True, default='', max_length=30)),
                ('company_address_1', models.CharField(blank=True, default='', max_length=600)),
                ('company_address_2', models.CharField(blank=True, default='', max_length=600)),
                ('company_city', models.CharField(blank=True, default='', max_length=600)),
                ('guest_photo', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('blood_group', models.CharField(blank=True, default='', max_length=10)),
                ('allergy_details', models.CharField(blank=True, default='', max_length=2000)),
                ('other_details', models.CharField(blank=True, default='', max_length=5000)),
                ('doctor_to_call', models.CharField(blank=True, default='', max_length=500)),
                ('emergency_contact_1_name', models.CharField(blank=True, default='', max_length=500)),
                ('emergency_contact_1_phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('emergency_contact_2_name', models.CharField(blank=True, default='', max_length=500)),
                ('emergency_contact_2_phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('parent_guardian_1_type', models.CharField(blank=True, choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('HUSBAND', 'Husband'), ('WIFE', 'Wife'), ('GUARDIAN', 'Guardian')], default='', max_length=10)),
                ('parent_guardian_1_name', models.CharField(blank=True, default='', max_length=500)),
                ('parent_guardian_1_qualifications', models.CharField(blank=True, default='', max_length=500)),
                ('parent_guardian_1_occupation', models.CharField(blank=True, default='', max_length=500)),
                ('parent_guardian_1_company', models.CharField(blank=True, default='', max_length=500)),
                ('parent_guardian_1_phone_number', models.CharField(blank=True, default='', max_length=500)),
                ('parent_guardian_1_email_id', models.EmailField(blank=True, default='', max_length=254)),
                ('parent_guardian_2_type', models.CharField(blank=True, choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('HUSBAND', 'Husband'), ('WIFE', 'Wife'), ('GUARDIAN', 'Guardian')], default='', max_length=10)),
                ('parent_guardian_2_name', models.CharField(blank=True, default='', max_length=500)),
                ('parent_guardian_2_qualifications', models.CharField(blank=True, default='', max_length=500)),
                ('parent_guardian_2_occupation', models.CharField(blank=True, default='', max_length=500)),
                ('parent_guardian_2_company', models.CharField(blank=True, default='', max_length=500)),
                ('parent_guardian_2_phone_number', models.CharField(blank=True, default='', max_length=500)),
                ('parent_guardian_2_email_id', models.EmailField(blank=True, default='', max_length=254)),
                ('parent_guardian_3_type', models.CharField(blank=True, choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('HUSBAND', 'Husband'), ('WIFE', 'Wife'), ('GUARDIAN', 'Guardian')], default='', max_length=10)),
                ('parent_guardian_3_name', models.CharField(blank=True, default='', max_length=500)),
                ('parent_guardian_3_qualifications', models.CharField(blank=True, default='', max_length=500)),
                ('parent_guardian_3_occupation', models.CharField(blank=True, default='', max_length=500)),
                ('parent_guardian_3_company', models.CharField(blank=True, default='', max_length=500)),
                ('parent_guardian_3_phone_number', models.CharField(blank=True, default='', max_length=500)),
                ('parent_guardian_3_email_id', models.EmailField(blank=True, default='', max_length=254)),
                ('company_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_addr_country', to='guesthouse.Country')),
                ('company_pin_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_addr_pin_code', to='guesthouse.Pin_code')),
                ('company_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_addr_state', to='guesthouse.State')),
                ('current_country', models.ForeignKey(default='IND', on_delete=django.db.models.deletion.PROTECT, related_name='current_addr_country', to='guesthouse.Country')),
                ('current_pin_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_addr_pin_code', to='guesthouse.Pin_code')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_addr_state', to='guesthouse.State')),
                ('permanent_country', models.ForeignKey(default='IND', on_delete=django.db.models.deletion.PROTECT, related_name='permanent_addr_country', to='guesthouse.Country')),
                ('permanent_pin_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permanent_pin_code', to='guesthouse.Pin_code')),
                ('permanent_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permanent_addr_state', to='guesthouse.State')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='company_address_1',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='company_address_2',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='company_city',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='company_contact_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='company_contact_person',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='company_country',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='company_pin_code',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='company_state',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='current_address_1',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='current_address_2',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='current_city',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='current_country',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='current_pin_code',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='current_state',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_photo',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='permanent_address_1',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='permanent_address_2',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='permanent_city',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='permanent_country',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='permanent_pin_code',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='permanent_state',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='food_opted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='food_preference',
            field=models.CharField(blank=True, choices=[('VEG', 'Vegetarian'), ('NOV-VEG', 'None-Vegetarian')], default='', max_length=7),
        ),
        migrations.AddField(
            model_name='booking',
            name='tenure',
            field=models.CharField(blank=True, choices=[('ONE-MONTH', 'One Month'), ('LONG-TERM', 'Long Term')], default='', max_length=7),
        ),
    ]
