# Generated by Django 2.1.4 on 2019-01-29 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0004_auto_20190129_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='updated_date',
            field=models.DateTimeField(default='2019-01-29'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='company_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_addr_country', to='guesthouse.Country'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='company_pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_addr_pin_code', to='guesthouse.Pin_code'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='company_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_addr_state', to='guesthouse.State'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='current_country',
            field=models.ForeignKey(default='IND', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_addr_country', to='guesthouse.Country'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='current_pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_addr_pin_code', to='guesthouse.Pin_code'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='current_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_addr_state', to='guesthouse.State'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='permanent_country',
            field=models.ForeignKey(default='IND', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_addr_country', to='guesthouse.Country'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='permanent_pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_pin_code', to='guesthouse.Pin_code'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='permanent_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_addr_state', to='guesthouse.State'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='updated_date',
            field=models.DateTimeField(default='2019-01-29'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room_allocation',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Bed'),
        ),
        migrations.AlterField(
            model_name='room_allocation',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Block'),
        ),
        migrations.AlterField(
            model_name='room_allocation',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Floor'),
        ),
        migrations.AlterField(
            model_name='room_allocation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Room'),
        ),
        migrations.AlterField(
            model_name='room_allocation',
            name='updated_date',
            field=models.DateTimeField(default='2019-01-29'),
            preserve_default=False,
        ),
    ]
