# Generated by Django 2.1.4 on 2019-01-29 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0005_auto_20190129_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guesthouse.Guest'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guesthouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guesthouse.Guesthouse'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='company_country',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_addr_country', to='guesthouse.Country'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='company_pin_code',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_addr_pin_code', to='guesthouse.Pin_code'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='company_state',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_addr_state', to='guesthouse.State'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='current_address_1',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='guest',
            name='current_country',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_addr_country', to='guesthouse.Country'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='current_pin_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_addr_pin_code', to='guesthouse.Pin_code'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='current_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_addr_state', to='guesthouse.State'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_photo',
            field=models.ImageField(blank=True, default='', upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='occupation',
            field=models.CharField(choices=[('SR', 'Working'), ('ST', 'Studying')], default='ST', max_length=2),
        ),
        migrations.AlterField(
            model_name='guest',
            name='permanent_country',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='permanent_addr_country', to='guesthouse.Country'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='permanent_pin_code',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='permanent_pin_code', to='guesthouse.Pin_code'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='permanent_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='permanent_addr_state', to='guesthouse.State'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room_allocation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room_allocation',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
