# Generated by Django 2.1.4 on 2019-01-31 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0006_auto_20190129_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='food_preference',
            field=models.CharField(blank=True, choices=[('VEG', 'Vegetarian'), ('NOV-VEG', 'None-Vegetarian')], default='VEG', max_length=7),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tenure',
            field=models.CharField(blank=True, choices=[('ONE-MONTH', 'One Month'), ('LONG-TERM', 'Long Term')], default='LONG-TERM', max_length=7),
        ),
        migrations.AlterField(
            model_name='guest',
            name='current_pin_code',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_addr_pin_code', to='guesthouse.Pin_code'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='current_state',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_addr_state', to='guesthouse.State'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='permanent_state',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='permanent_addr_state', to='guesthouse.State'),
        ),
    ]
