# Generated by Django 2.1.4 on 2019-01-31 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0008_auto_20190131_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='company_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_addr_country', to='guesthouse.Country'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='company_pin_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_addr_pin_code', to='guesthouse.Pin_code'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='company_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_addr_state', to='guesthouse.State'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='current_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_addr_country', to='guesthouse.Country'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='current_pin_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_addr_pin_code', to='guesthouse.Pin_code'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_addr_state', to='guesthouse.State'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='permanent_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='permanent_addr_country', to='guesthouse.Country'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='permanent_pin_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='permanent_pin_code', to='guesthouse.Pin_code'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='permanent_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='permanent_addr_state', to='guesthouse.State'),
        ),
    ]
