# Generated by Django 2.1.4 on 2019-02-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0009_auto_20190131_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_out_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='doctor_contact_number',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
