# Generated by Django 2.1.4 on 2019-02-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0010_auto_20190201_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='FEMALE', max_length=6),
        ),
    ]
