# Generated by Django 2.1.4 on 2019-02-01 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0011_guest_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room_allocation',
            name='allocation_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room_allocation',
            name='allocation_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room_allocation',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Bed'),
        ),
        migrations.AlterField(
            model_name='room_allocation',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Block'),
        ),
        migrations.AlterField(
            model_name='room_allocation',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Floor'),
        ),
        migrations.AlterField(
            model_name='room_allocation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Room'),
        ),
    ]
