# Generated by Django 2.1.4 on 2019-02-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0012_auto_20190201_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tenure',
            field=models.CharField(blank=True, choices=[('ST', 'One Month'), ('LT', 'Long Term')], default='LT', max_length=2),
        ),
    ]
