# Generated by Django 2.1.4 on 2019-02-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0013_auto_20190201_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generate_number_by_month',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('month_year', models.CharField(max_length=6)),
                ('current_number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='guest',
            name='permanent_pin_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='permanent_addr_pin_code', to='guesthouse.Pin_code'),
        ),
    ]
