# Generated by Django 2.1.4 on 2019-02-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0015_guesthouse_month_year_suffix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_in_datetime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out_datetime',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
