# Generated by Django 2.1.4 on 2019-02-17 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0017_auto_20190212_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_option', models.BooleanField(default=False)),
                ('food_preference', models.CharField(blank=True, choices=[('VEG', 'Vegetarian'), ('NOV-VEG', 'Non-Vegetarian')], default='VEG', max_length=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('booking_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guesthouse.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('tax_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('guesthouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guesthouse.Guesthouse')),
            ],
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_name',
            field=models.CharField(max_length=100),
        ),
    ]
