# Generated by Django 2.1.4 on 2019-03-15 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0021_auto_20190311_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='bill',
            field=models.ForeignKey(blank=True, help_text='Payment againt bill', null=True, on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Bill'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_for',
            field=models.CharField(choices=[('RN', 'Monthly Rent'), ('AD', 'Advance Payment'), ('AR', 'Advance Rent Payment'), ('BK', 'Blocking Advance'), ('FD', 'Food Service'), ('OT', 'Other Services')], max_length=2),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_for_month',
            field=models.CharField(blank=True, default='', help_text='Payment month (YYYY-MM)', max_length=6),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(help_text='Auto Generated', max_length=15),
        ),
        migrations.AlterField(
            model_name='room_allocation',
            name='allocation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room_allocation',
            name='allocation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
