# Generated by Django 2.1.4 on 2019-03-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0022_auto_20190315_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_food',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking_food',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
