# Generated by Django 2.1.4 on 2019-03-16 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0023_auto_20190315_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_for',
            field=models.CharField(choices=[('RN', 'Monthly Rent'), ('AD', 'Advance Payment'), ('AR', 'Advance Rent Payment'), ('BK', 'Blocking Advance'), ('FD', 'Food Service'), ('OT', 'Other Services')], max_length=2),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_for_month',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='bill',
            field=models.ForeignKey(blank=True, help_text='Select bill againt which Payment is being made', null=True, on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Bill'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_for_month',
            field=models.CharField(blank=True, default='', help_text='Payment month (YYYY-MM)', max_length=7),
        ),
    ]
