# Generated by Django 2.1.4 on 2019-03-18 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0024_auto_20190316_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_error',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_number', models.CharField(blank=True, default='', max_length=15)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('bill_for_month', models.CharField(max_length=7)),
                ('bill_for', models.CharField(blank=True, choices=[('RN', 'Monthly Rent'), ('AD', 'Advance Payment'), ('AR', 'Advance Rent Payment'), ('BK', 'Blocking Advance'), ('FD', 'Food Service'), ('OT', 'Other Services')], default='', max_length=2)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('error', models.CharField(blank=True, default='', max_length=2000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='guesthouse.Booking')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='guesthouse.Guest')),
            ],
        ),
    ]
