# Generated by Django 2.1.4 on 2019-03-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0025_billing_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_price',
            name='vacation_period_price',
            field=models.DecimalField(decimal_places=2, default=1250, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='short_term_rent_per_bed',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room_conversion',
            name='short_term_rent_per_bed',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=12),
            preserve_default=False,
        ),
    ]
