# Generated by Django 2.1.4 on 2019-03-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0026_auto_20190319_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='account_closed',
            field=models.BooleanField(default=False),
        ),
    ]
