# Generated by Django 2.1.4 on 2019-03-28 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0027_booking_account_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closing_balance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('closing_balance_month', models.CharField(help_text='Closing Balance as of end of month (YYYY-MM)', max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Booking')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='Month_closing_error',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('closing_balance_month', models.CharField(max_length=7)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('error', models.CharField(blank=True, default='', max_length=2000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='guesthouse.Booking')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='guesthouse.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='Occupancy_dashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('occupied', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guesthouse.Bed')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guesthouse.Block')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='guesthouse.Booking')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guesthouse.Floor')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guesthouse.Guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guesthouse.Room')),
            ],
        ),
    ]
