# Generated by Django 2.1.4 on 2019-03-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0028_closing_balance_month_closing_error_occupancy_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupancy_dashboard',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='occupancy_dashboard',
            name='guest',
        ),
    ]
