# Generated by Django 2.1.4 on 2019-03-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0029_auto_20190328_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacate',
            fields=[
                ('vacate_id', models.AutoField(primary_key=True, serialize=False)),
                ('vacate_date', models.DateField()),
                ('maintenance_deductions', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rent_arrears_deductions', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('other_deductions', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rental_payment_status', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_payable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('refund_mode_of_payment', models.CharField(blank=True, choices=[('CS', 'Cash'), ('ON', 'Online'), ('CH', 'Cheque'), ('DD', 'Demand Draft')], max_length=2, null=True)),
                ('refund_cheque_dd_in_favour_of', models.CharField(blank=True, default='', max_length=600)),
                ('refund_cheque_dd_no', models.CharField(blank=True, default='', max_length=15)),
                ('refund_cheque_dd_date', models.DateField(blank=True, null=True)),
                ('refund_bank_acc_no', models.CharField(blank=True, default='', max_length=20)),
                ('refund_ifsc_code', models.CharField(blank=True, default='', max_length=10)),
                ('refund_bank_name', models.CharField(blank=True, default='', max_length=500)),
                ('refund_bank_branch', models.CharField(blank=True, default='', max_length=600)),
                ('refund_reference', models.CharField(blank=True, default='', max_length=500)),
                ('statement_prepared_by', models.CharField(blank=True, default='', max_length=500)),
                ('management_approval_by', models.CharField(blank=True, default='', max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('room_alloc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Room_allocation')),
            ],
        ),
        migrations.AddField(
            model_name='occupancy_dashboard',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='mode_of_payment',
            field=models.CharField(choices=[('CS', 'Cash'), ('ON', 'Online'), ('CH', 'Cheque'), ('DD', 'Demand Draft')], max_length=2),
        ),
    ]
