# Generated by Django 2.1.4 on 2019-04-04 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0030_auto_20190330_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_food',
            name='food_preference',
            field=models.CharField(blank=True, choices=[('VEG', 'Vegetarian'), ('NON-VEG', 'Non-Vegetarian')], default='VEG', max_length=7),
        ),
        migrations.AlterField(
            model_name='vacate',
            name='rental_payment_status',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='vacate',
            name='room_alloc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Room_allocation'),
        ),
    ]
