# Generated by Django 2.1.4 on 2019-04-15 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0032_auto_20190408_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills_receipts_dashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expected_advance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('advance_rct', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rent_rct', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_food_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('food_charges_rct', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('outstanding_31Mar', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('outstanding_amont', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guesthouse.Bed')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guesthouse.Block')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guesthouse.Booking')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guesthouse.Floor')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guesthouse.Guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guesthouse.Room')),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_for',
            field=models.CharField(choices=[('RN', 'Monthly Rent'), ('AD', 'Advance Payment'), ('AR', 'Advance Rent Payment'), ('BK', 'Blocking Advance'), ('FD', 'Food Service'), ('OS', 'Outstanding'), ('OT', 'Other Services')], max_length=2),
        ),
        migrations.AlterField(
            model_name='vacate',
            name='room_alloc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Room_allocation'),
        ),
    ]
