# Generated by Django 2.1.4 on 2019-04-19 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guesthouse', '0036_auto_20190418_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.PositiveSmallIntegerField(choices=[(1, 'Transport'), (2, 'PG'), (3, 'Accounts')], null=True)),
                ('is_manager', models.BooleanField(default=False, verbose_name='manager status')),
                ('is_ceo', models.BooleanField(default=False, verbose_name='ceo status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='vacate',
            name='room_alloc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Room_allocation'),
        ),
    ]
