# Generated by Django 2.1.4 on 2019-04-24 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0037_auto_20190419_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills_receipts_dashboard',
            name='os_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_for',
            field=models.CharField(choices=[('RN', 'Monthly Rent'), ('AD', 'Advance Payment'), ('AR', 'Advance Rent Payment'), ('BK', 'Blocking Advance'), ('FD', 'Food Service'), ('OS', 'Outstanding'), ('OT', 'Other Services')], max_length=2),
        ),
        migrations.AlterField(
            model_name='vacate',
            name='room_alloc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Room_allocation'),
        ),
    ]
