# Generated by Django 2.1.4 on 2019-04-29 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0038_auto_20190424_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rates_effective_from',
            field=models.DateField(default='2015-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='rates_effective_to',
            field=models.DateField(default='2099-12-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='short_term_advance',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room_conversion',
            name='rates_effective_from',
            field=models.DateField(default='2015-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room_conversion',
            name='rates_effective_to',
            field=models.DateField(default='2099-12-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room_conversion',
            name='short_term_advance',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='available_from',
            field=models.DateField(default='2015-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='available_to',
            field=models.DateField(default='2099-12-31'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacate',
            name='room_alloc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Room_allocation'),
        ),
    ]
