# Generated by Django 2.1.4 on 2019-05-09 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0041_auto_20190503_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory_conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('U', 'Upper'), ('L', 'Lower')], default='', max_length=1, null=True)),
                ('rent_per_bed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('short_term_rent_per_bed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('short_term_advance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rates_effective_from', models.DateField()),
                ('rates_effective_to', models.DateField()),
                ('bed', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Bed')),
                ('block', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='guesthouse.Block')),
                ('floor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='guesthouse.Floor')),
                ('room', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='guesthouse.Room')),
            ],
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='birthday_card',
            field=models.ImageField(null=True, upload_to='card/'),
        ),
        migrations.AlterField(
            model_name='vacate',
            name='room_alloc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guesthouse.Room_allocation'),
        ),
    ]
